services:
  - type: web
    name: polyverse
    env: python
    plan: free
    rootDir: backend
    buildCommand: "pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt"
    startCommand: "gunicorn predictapi:app"
    pythonVersion: 3.10.14
